# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/admin/Documents/GitHub/AdrenalineEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/admin/Documents/Github/AdrenalineEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/admin/Documents/Github/AdrenalineEngine/CMakeFiles /Users/admin/Documents/Github/AdrenalineEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/admin/Documents/Github/AdrenalineEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Adrenaline-Engine

# Build rule for target.
Adrenaline-Engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Adrenaline-Engine
.PHONY : Adrenaline-Engine

# fast build rule for target.
Adrenaline-Engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/build
.PHONY : Adrenaline-Engine/fast

engine/adrenaline.o: engine/adrenaline.cpp.o

.PHONY : engine/adrenaline.o

# target to build an object file
engine/adrenaline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/adrenaline.cpp.o
.PHONY : engine/adrenaline.cpp.o

engine/adrenaline.i: engine/adrenaline.cpp.i

.PHONY : engine/adrenaline.i

# target to preprocess a source file
engine/adrenaline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/adrenaline.cpp.i
.PHONY : engine/adrenaline.cpp.i

engine/adrenaline.s: engine/adrenaline.cpp.s

.PHONY : engine/adrenaline.s

# target to generate assembly for a file
engine/adrenaline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/adrenaline.cpp.s
.PHONY : engine/adrenaline.cpp.s

engine/renderer/debugging.o: engine/renderer/debugging.cpp.o

.PHONY : engine/renderer/debugging.o

# target to build an object file
engine/renderer/debugging.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/debugging.cpp.o
.PHONY : engine/renderer/debugging.cpp.o

engine/renderer/debugging.i: engine/renderer/debugging.cpp.i

.PHONY : engine/renderer/debugging.i

# target to preprocess a source file
engine/renderer/debugging.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/debugging.cpp.i
.PHONY : engine/renderer/debugging.cpp.i

engine/renderer/debugging.s: engine/renderer/debugging.cpp.s

.PHONY : engine/renderer/debugging.s

# target to generate assembly for a file
engine/renderer/debugging.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/debugging.cpp.s
.PHONY : engine/renderer/debugging.cpp.s

engine/renderer/devices.o: engine/renderer/devices.cpp.o

.PHONY : engine/renderer/devices.o

# target to build an object file
engine/renderer/devices.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/devices.cpp.o
.PHONY : engine/renderer/devices.cpp.o

engine/renderer/devices.i: engine/renderer/devices.cpp.i

.PHONY : engine/renderer/devices.i

# target to preprocess a source file
engine/renderer/devices.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/devices.cpp.i
.PHONY : engine/renderer/devices.cpp.i

engine/renderer/devices.s: engine/renderer/devices.cpp.s

.PHONY : engine/renderer/devices.s

# target to generate assembly for a file
engine/renderer/devices.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/devices.cpp.s
.PHONY : engine/renderer/devices.cpp.s

engine/renderer/display.o: engine/renderer/display.cpp.o

.PHONY : engine/renderer/display.o

# target to build an object file
engine/renderer/display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/display.cpp.o
.PHONY : engine/renderer/display.cpp.o

engine/renderer/display.i: engine/renderer/display.cpp.i

.PHONY : engine/renderer/display.i

# target to preprocess a source file
engine/renderer/display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/display.cpp.i
.PHONY : engine/renderer/display.cpp.i

engine/renderer/display.s: engine/renderer/display.cpp.s

.PHONY : engine/renderer/display.s

# target to generate assembly for a file
engine/renderer/display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/display.cpp.s
.PHONY : engine/renderer/display.cpp.s

engine/renderer/model.o: engine/renderer/model.cpp.o

.PHONY : engine/renderer/model.o

# target to build an object file
engine/renderer/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/model.cpp.o
.PHONY : engine/renderer/model.cpp.o

engine/renderer/model.i: engine/renderer/model.cpp.i

.PHONY : engine/renderer/model.i

# target to preprocess a source file
engine/renderer/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/model.cpp.i
.PHONY : engine/renderer/model.cpp.i

engine/renderer/model.s: engine/renderer/model.cpp.s

.PHONY : engine/renderer/model.s

# target to generate assembly for a file
engine/renderer/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/model.cpp.s
.PHONY : engine/renderer/model.cpp.s

engine/renderer/pipeline.o: engine/renderer/pipeline.cpp.o

.PHONY : engine/renderer/pipeline.o

# target to build an object file
engine/renderer/pipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/pipeline.cpp.o
.PHONY : engine/renderer/pipeline.cpp.o

engine/renderer/pipeline.i: engine/renderer/pipeline.cpp.i

.PHONY : engine/renderer/pipeline.i

# target to preprocess a source file
engine/renderer/pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/pipeline.cpp.i
.PHONY : engine/renderer/pipeline.cpp.i

engine/renderer/pipeline.s: engine/renderer/pipeline.cpp.s

.PHONY : engine/renderer/pipeline.s

# target to generate assembly for a file
engine/renderer/pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/pipeline.cpp.s
.PHONY : engine/renderer/pipeline.cpp.s

engine/renderer/processing.o: engine/renderer/processing.cpp.o

.PHONY : engine/renderer/processing.o

# target to build an object file
engine/renderer/processing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/processing.cpp.o
.PHONY : engine/renderer/processing.cpp.o

engine/renderer/processing.i: engine/renderer/processing.cpp.i

.PHONY : engine/renderer/processing.i

# target to preprocess a source file
engine/renderer/processing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/processing.cpp.i
.PHONY : engine/renderer/processing.cpp.i

engine/renderer/processing.s: engine/renderer/processing.cpp.s

.PHONY : engine/renderer/processing.s

# target to generate assembly for a file
engine/renderer/processing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/processing.cpp.s
.PHONY : engine/renderer/processing.cpp.s

engine/renderer/renderer.o: engine/renderer/renderer.cpp.o

.PHONY : engine/renderer/renderer.o

# target to build an object file
engine/renderer/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/renderer.cpp.o
.PHONY : engine/renderer/renderer.cpp.o

engine/renderer/renderer.i: engine/renderer/renderer.cpp.i

.PHONY : engine/renderer/renderer.i

# target to preprocess a source file
engine/renderer/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/renderer.cpp.i
.PHONY : engine/renderer/renderer.cpp.i

engine/renderer/renderer.s: engine/renderer/renderer.cpp.s

.PHONY : engine/renderer/renderer.s

# target to generate assembly for a file
engine/renderer/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/engine/renderer/renderer.cpp.s
.PHONY : engine/renderer/renderer.cpp.s

lib/imgui/imgui.o: lib/imgui/imgui.cpp.o

.PHONY : lib/imgui/imgui.o

# target to build an object file
lib/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui.cpp.o
.PHONY : lib/imgui/imgui.cpp.o

lib/imgui/imgui.i: lib/imgui/imgui.cpp.i

.PHONY : lib/imgui/imgui.i

# target to preprocess a source file
lib/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui.cpp.i
.PHONY : lib/imgui/imgui.cpp.i

lib/imgui/imgui.s: lib/imgui/imgui.cpp.s

.PHONY : lib/imgui/imgui.s

# target to generate assembly for a file
lib/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui.cpp.s
.PHONY : lib/imgui/imgui.cpp.s

lib/imgui/imgui_demo.o: lib/imgui/imgui_demo.cpp.o

.PHONY : lib/imgui/imgui_demo.o

# target to build an object file
lib/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_demo.cpp.o
.PHONY : lib/imgui/imgui_demo.cpp.o

lib/imgui/imgui_demo.i: lib/imgui/imgui_demo.cpp.i

.PHONY : lib/imgui/imgui_demo.i

# target to preprocess a source file
lib/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_demo.cpp.i
.PHONY : lib/imgui/imgui_demo.cpp.i

lib/imgui/imgui_demo.s: lib/imgui/imgui_demo.cpp.s

.PHONY : lib/imgui/imgui_demo.s

# target to generate assembly for a file
lib/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_demo.cpp.s
.PHONY : lib/imgui/imgui_demo.cpp.s

lib/imgui/imgui_draw.o: lib/imgui/imgui_draw.cpp.o

.PHONY : lib/imgui/imgui_draw.o

# target to build an object file
lib/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_draw.cpp.o
.PHONY : lib/imgui/imgui_draw.cpp.o

lib/imgui/imgui_draw.i: lib/imgui/imgui_draw.cpp.i

.PHONY : lib/imgui/imgui_draw.i

# target to preprocess a source file
lib/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_draw.cpp.i
.PHONY : lib/imgui/imgui_draw.cpp.i

lib/imgui/imgui_draw.s: lib/imgui/imgui_draw.cpp.s

.PHONY : lib/imgui/imgui_draw.s

# target to generate assembly for a file
lib/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_draw.cpp.s
.PHONY : lib/imgui/imgui_draw.cpp.s

lib/imgui/imgui_impl_glfw.o: lib/imgui/imgui_impl_glfw.cpp.o

.PHONY : lib/imgui/imgui_impl_glfw.o

# target to build an object file
lib/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_impl_glfw.cpp.o
.PHONY : lib/imgui/imgui_impl_glfw.cpp.o

lib/imgui/imgui_impl_glfw.i: lib/imgui/imgui_impl_glfw.cpp.i

.PHONY : lib/imgui/imgui_impl_glfw.i

# target to preprocess a source file
lib/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_impl_glfw.cpp.i
.PHONY : lib/imgui/imgui_impl_glfw.cpp.i

lib/imgui/imgui_impl_glfw.s: lib/imgui/imgui_impl_glfw.cpp.s

.PHONY : lib/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
lib/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_impl_glfw.cpp.s
.PHONY : lib/imgui/imgui_impl_glfw.cpp.s

lib/imgui/imgui_impl_vulkan.o: lib/imgui/imgui_impl_vulkan.cpp.o

.PHONY : lib/imgui/imgui_impl_vulkan.o

# target to build an object file
lib/imgui/imgui_impl_vulkan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_impl_vulkan.cpp.o
.PHONY : lib/imgui/imgui_impl_vulkan.cpp.o

lib/imgui/imgui_impl_vulkan.i: lib/imgui/imgui_impl_vulkan.cpp.i

.PHONY : lib/imgui/imgui_impl_vulkan.i

# target to preprocess a source file
lib/imgui/imgui_impl_vulkan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_impl_vulkan.cpp.i
.PHONY : lib/imgui/imgui_impl_vulkan.cpp.i

lib/imgui/imgui_impl_vulkan.s: lib/imgui/imgui_impl_vulkan.cpp.s

.PHONY : lib/imgui/imgui_impl_vulkan.s

# target to generate assembly for a file
lib/imgui/imgui_impl_vulkan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_impl_vulkan.cpp.s
.PHONY : lib/imgui/imgui_impl_vulkan.cpp.s

lib/imgui/imgui_tables.o: lib/imgui/imgui_tables.cpp.o

.PHONY : lib/imgui/imgui_tables.o

# target to build an object file
lib/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_tables.cpp.o
.PHONY : lib/imgui/imgui_tables.cpp.o

lib/imgui/imgui_tables.i: lib/imgui/imgui_tables.cpp.i

.PHONY : lib/imgui/imgui_tables.i

# target to preprocess a source file
lib/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_tables.cpp.i
.PHONY : lib/imgui/imgui_tables.cpp.i

lib/imgui/imgui_tables.s: lib/imgui/imgui_tables.cpp.s

.PHONY : lib/imgui/imgui_tables.s

# target to generate assembly for a file
lib/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_tables.cpp.s
.PHONY : lib/imgui/imgui_tables.cpp.s

lib/imgui/imgui_widgets.o: lib/imgui/imgui_widgets.cpp.o

.PHONY : lib/imgui/imgui_widgets.o

# target to build an object file
lib/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_widgets.cpp.o
.PHONY : lib/imgui/imgui_widgets.cpp.o

lib/imgui/imgui_widgets.i: lib/imgui/imgui_widgets.cpp.i

.PHONY : lib/imgui/imgui_widgets.i

# target to preprocess a source file
lib/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_widgets.cpp.i
.PHONY : lib/imgui/imgui_widgets.cpp.i

lib/imgui/imgui_widgets.s: lib/imgui/imgui_widgets.cpp.s

.PHONY : lib/imgui/imgui_widgets.s

# target to generate assembly for a file
lib/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/lib/imgui/imgui_widgets.cpp.s
.PHONY : lib/imgui/imgui_widgets.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Adrenaline-Engine.dir/build.make CMakeFiles/Adrenaline-Engine.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Adrenaline-Engine"
	@echo "... engine/adrenaline.o"
	@echo "... engine/adrenaline.i"
	@echo "... engine/adrenaline.s"
	@echo "... engine/renderer/debugging.o"
	@echo "... engine/renderer/debugging.i"
	@echo "... engine/renderer/debugging.s"
	@echo "... engine/renderer/devices.o"
	@echo "... engine/renderer/devices.i"
	@echo "... engine/renderer/devices.s"
	@echo "... engine/renderer/display.o"
	@echo "... engine/renderer/display.i"
	@echo "... engine/renderer/display.s"
	@echo "... engine/renderer/model.o"
	@echo "... engine/renderer/model.i"
	@echo "... engine/renderer/model.s"
	@echo "... engine/renderer/pipeline.o"
	@echo "... engine/renderer/pipeline.i"
	@echo "... engine/renderer/pipeline.s"
	@echo "... engine/renderer/processing.o"
	@echo "... engine/renderer/processing.i"
	@echo "... engine/renderer/processing.s"
	@echo "... engine/renderer/renderer.o"
	@echo "... engine/renderer/renderer.i"
	@echo "... engine/renderer/renderer.s"
	@echo "... lib/imgui/imgui.o"
	@echo "... lib/imgui/imgui.i"
	@echo "... lib/imgui/imgui.s"
	@echo "... lib/imgui/imgui_demo.o"
	@echo "... lib/imgui/imgui_demo.i"
	@echo "... lib/imgui/imgui_demo.s"
	@echo "... lib/imgui/imgui_draw.o"
	@echo "... lib/imgui/imgui_draw.i"
	@echo "... lib/imgui/imgui_draw.s"
	@echo "... lib/imgui/imgui_impl_glfw.o"
	@echo "... lib/imgui/imgui_impl_glfw.i"
	@echo "... lib/imgui/imgui_impl_glfw.s"
	@echo "... lib/imgui/imgui_impl_vulkan.o"
	@echo "... lib/imgui/imgui_impl_vulkan.i"
	@echo "... lib/imgui/imgui_impl_vulkan.s"
	@echo "... lib/imgui/imgui_tables.o"
	@echo "... lib/imgui/imgui_tables.i"
	@echo "... lib/imgui/imgui_tables.s"
	@echo "... lib/imgui/imgui_widgets.o"
	@echo "... lib/imgui/imgui_widgets.i"
	@echo "... lib/imgui/imgui_widgets.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

